meta:
  - ['!.gitignore', '!Makefile', '!.markdownlint.jsonc'] # ignore
  - ['/.github/**/*', '/.circleci/*', '*.md'] #include

documentaion:
 - '/**/*.md'

greedy-algorithm:
  - '/greedy-algorithm/**/*'

ford-Fulkerson-algorithm:
  - '/ford-Fulkerson-algorithm/**/*'

dijkstra's-algorithm:
 - |
      dijkstra's-algorithm/**/*'
