## GitHub Pages configuration

title: Algorithms # site title
description: Implementaion of popular Algrotihms in C++ # site description
remote_theme: pages-themes/slate@v0.2.0 # use slate theme
show_downloads: true # show download buttons
