version: 2.1

dependencies:
  pre:
    - sudo apt-get update; sudo apt-get remove llvm-3.0; sudo apt-get install llvm-3.4 libclang1-3.4 llvm-3.4-dev
 
jobs:
  compile:
    machine: true
    steps:
      - checkout
      - run: |
          make compile

workflows:
  compile-workflow:
    jobs:
      - compile