version: 2.1

jobs:
  echo-clang-version:
    machine: true
    steps:
      - checkout
      - run: |
          clang++ --version

#   dependencies:
#     machine: true
#     steps: 
#       - run: |
#           sudo apt-get update; sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      
  # compile:
  #   machine: true
  #   steps:
  #     - checkout
  #     - run: |
  #         make compile



workflows:
  compile-workflow:
    jobs:
      - echo-clang-version