version: 2.1

jobs: 
  echo-clang-version:
    machine: true
    steps:
      - checkout
      - run: |
          clang++ --version

  install-dependencies:
    machine: true
    steps:
      - run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

#   dependencies:
#     machine: true
#     steps: 
#       - run: |
#           sudo apt-get update; sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      
  # compile:
  #   machine: true
  #   steps:
  #     - checkout
  #     - run: |
  #         make compile



workflows:
  compile-workflow:
    jobs:
      - install-dependencies
      - echo-clang-version:
          requires:
                - install-dependencies
