version: 2.1

jobs:
  verify-env:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: |
          gcc --version
  
  # compile:
  #   machine: true
  #   steps:
  #     - checkout
  #     - run: |
  #         make compile

workflows:
  compile-workflow:
    jobs:
      - verify-env