version: 2.1
 
jobs:
  setup-env:
    machine: true
    steps:
      - run: |
          sudo apt-get clang++

  compile:
    machine: true
    steps:
      - checkout
      - run: |
          make compile

workflows:
  compile-workflow:
    jobs:
      - setup-env
      - compile