version: 2.1

jobs:
  dependencies:
    machine: true
    steps: 
      - run: |
          sudo apt-get update # get updates
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" # install llmvn
      
  compile:
    machine: true
    steps:
      - checkout
      - run: |
          make compile

workflows:
  compile-workflow:
    jobs:
      - dependencies
      - compile