version: 2.1
    
jobs:
  compile:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run: |
          make compile

workflows:
  compile-workflow:
    jobs:
      - compile